{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Chapter 4 - Loops"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### There are several techniques to repeatedly execute Python code. While loops are like repeated if statements; the for loop is there to iterate over all kinds of data structures. Learn all about them in this chapter."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### while: warming up\n",
    "The while loop is like a repeated if statement. The code is executed over and over again, as long as the condition is True. Have another look at its recipe.\n",
    "\n",
    "```python\n",
    "while condition :\n",
    "    expression\n",
    "```\n",
    "Can you tell how many printouts the following while loop will do?\n",
    "\n",
    "```python\n",
    "x = 1\n",
    "while x < 4 :\n",
    "    print(x)\n",
    "    x = x + 1\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "__Answer__: 3"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "Correct! After 3 runs, x will be equal to 4, causing x < 4 to evaluate to False. This means that the while loop is executed 3 times, giving three printouts."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Basic while loop\n",
    "Below you can find the example where the error variable, initially equal to 50.0, is divided by 4 and printed out on every run:\n",
    "\n",
    "```python\n",
    "error = 50.0\n",
    "while error > 1 :\n",
    "    error = error / 4\n",
    "    print(error)\n",
    "```\n",
    "This example will come in handy, because it's time to build a while loop yourself! We're going to code a while loop that implements a very basic control system for an inverted pendulum. If there's an offset from standing perfectly straight, the while loop will incrementally fix this offset"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "correcting...\n",
      "7\n",
      "correcting...\n",
      "6\n",
      "correcting...\n",
      "5\n",
      "correcting...\n",
      "4\n",
      "correcting...\n",
      "3\n",
      "correcting...\n",
      "2\n",
      "correcting...\n",
      "1\n",
      "correcting...\n",
      "0\n"
     ]
    }
   ],
   "source": [
    "# Initialize offset\n",
    "offset = 8\n",
    "\n",
    "# Code the while loop\n",
    "while offset !=0:\n",
    "    print('correcting...')\n",
    "    offset -= 1\n",
    "    print(offset)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Add conditionals\n",
    "The while loop that corrects the offset is a good start, but what if offset is negative? You can try to run the following code where offset is initialized to -6:\n",
    "\n",
    "```python\n",
    "# Initialize offset\n",
    "offset = -6\n",
    "\n",
    "# Code the while loop\n",
    "while offset != 0 :\n",
    "    print(\"correcting...\")\n",
    "    offset = offset - 1\n",
    "    print(offset)\n",
    "```\n",
    "but your session will be disconnected. The while loop will never stop running, because offset will be further decreased on every run. offset != 0 will never become False and the while loop continues forever.\n",
    "\n",
    "Fix things by putting an if-else statement inside the while loop."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "correcting...\n",
      "-5\n",
      "correcting...\n",
      "-4\n",
      "correcting...\n",
      "-3\n",
      "correcting...\n",
      "-2\n",
      "correcting...\n",
      "-1\n",
      "correcting...\n",
      "0\n"
     ]
    }
   ],
   "source": [
    "# Initialize offset\n",
    "offset = -6\n",
    "\n",
    "# Code the while loop\n",
    "while offset != 0 :\n",
    "    print(\"correcting...\")\n",
    "    if offset > 0:\n",
    "        offset -= 1 \n",
    "    else:\n",
    "        offset += 1\n",
    "    print(offset)"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "Good work! The while loop is not that often used in Data Science, so let's head over to the for loop."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Loop over a list\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "11.25\n",
      "18.0\n",
      "20.0\n",
      "10.75\n",
      "9.5\n"
     ]
    }
   ],
   "source": [
    "# areas list\n",
    "areas = [11.25, 18.0, 20.0, 10.75, 9.50]\n",
    "\n",
    "# Code the for loop\n",
    "for elements in areas:\n",
    "    print(elements)"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "Great! That wasn't too hard, was it?"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Indexes and values (1)\n",
    "Using a for loop to iterate over a list only gives you access to every list element in each run, one after the other. If you also want to access the index information, so where the list element you're iterating over is located, you can use enumerate().\n",
    "\n",
    "As an example, have a look:\n",
    "\n",
    "```python\n",
    "fam = [1.73, 1.68, 1.71, 1.89]\n",
    "for index, height in enumerate(fam) :\n",
    "    print(\"person \" + str(index) + \": \" + str(height))\n",
    "```"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "room 0 : 11.25\n",
      "room 1 : 18.0\n",
      "room 2 : 20.0\n",
      "room 3 : 10.75\n",
      "room 4 : 9.5\n"
     ]
    }
   ],
   "source": [
    "# areas list\n",
    "areas = [11.25, 18.0, 20.0, 10.75, 9.50]\n",
    "\n",
    "# Change for loop to use enumerate() and update print()\n",
    "for index, value in enumerate(areas) :\n",
    "    print(\"room\", index,\":\",value)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Indexes and values (2)\n",
    "For non-programmer folks, room 0: 11.25 is strange. Wouldn't it be better if the count started at 1?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "room 1: 11.25\n",
      "room 2: 18.0\n",
      "room 3: 20.0\n",
      "room 4: 10.75\n",
      "room 5: 9.5\n"
     ]
    }
   ],
   "source": [
    "# Code the for loop\n",
    "for index, area in enumerate(areas) :\n",
    "    print(\"room \" + str(index+1) + \": \" + str(area))"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "Much better!"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Loop over list of lists\n",
    "Remember the house variable from the Intro to Python course? . It's basically a list of lists, where each sublist contains the name and area of a room in your house.\n",
    "\n",
    "It's up to you to build a for loop from scratch this time!"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "the  hallway  is 11.25 sqm\n",
      "the  kitchen  is 18.0 sqm\n",
      "the  living room  is 20.0 sqm\n",
      "the  bedroom  is 10.75 sqm\n",
      "the  bathroom  is 9.5 sqm\n"
     ]
    }
   ],
   "source": [
    "# house list of lists\n",
    "house = [[\"hallway\", 11.25], \n",
    "         [\"kitchen\", 18.0], \n",
    "         [\"living room\", 20.0], \n",
    "         [\"bedroom\", 10.75], \n",
    "         [\"bathroom\", 9.50]]\n",
    "         \n",
    "# Build a for loop from scratch\n",
    "for name in house:\n",
    "    print(\"the \",name[0],\" is\", name[1], \"sqm\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Loop over dictionary\n",
    "In Python 3, you need the items() method to loop over a dictionary:\n",
    "\n",
    "```python\n",
    "world = { \"afghanistan\":30.55, \n",
    "          \"albania\":2.77,\n",
    "          \"algeria\":39.21 }\n",
    "\n",
    "for key, value in world.items() :\n",
    "    print(key + \" -- \" + str(value))\n",
    "```\n",
    "Remember the europe dictionary that contained the names of some European countries as key and their capitals as corresponding value? Go ahead and write a loop to iterate over it!"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "the capital of  spain is madrid\n",
      "the capital of  france is paris\n",
      "the capital of  germany is berlin\n",
      "the capital of  norway is oslo\n",
      "the capital of  italy is rome\n",
      "the capital of  poland is warsaw\n",
      "the capital of  austria is vienna\n"
     ]
    }
   ],
   "source": [
    "# Definition of dictionary\n",
    "europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin',\n",
    "          'norway':'oslo', 'italy':'rome', 'poland':'warsaw', 'austria':'vienna' }\n",
    "          \n",
    "# Iterate over europe\n",
    "for key, value in europe.items():\n",
    "    print(\"the capital of \",key,\"is\", value)"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "Great! Notice that the order of the printouts doesn't necessarily correspond with the order used when defining europe. Remember: dictionaries are inherently unordered!"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Loop over Numpy array\n",
    "If you're dealing with a 1D Numpy array, looping over all elements can be as simple as:\n",
    "\n",
    "```python\n",
    "for x in my_array :\n",
    "    ...\n",
    "```\n",
    "If you're dealing with a 2D Numpy array, it's more complicated. A 2D array is built up of multiple 1D arrays. To explicitly iterate over all separate elements of a multi-dimensional array, you'll need this syntax:\n",
    "\n",
    "```python\n",
    "for x in np.nditer(my_array) :\n",
    "    ...\n",
    "```\n",
    "Two Numpy arrays that you might recognize from the intro course are available in your Python session: np_height, a Numpy array containing the heights of Major League Baseball players, and np_baseball, a 2D Numpy array that contains both the heights (first column) and weights (second column) of those players."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [],
   "source": [
    "np_height = np.array([74,74,72,72,73,69,69,71,76,71,73,73,74,74,69,70,73,75,78,79,76,74,76,72,71,75,77,74,73,74,78,73,75,73,75,75,74,69,71,74,73,73,76,74,74,70,72,77\n",
    ",74,70,73,75,76,76,78,74,74,76,77,81,78,75,77,75,76,74,72,72,75,73,73,73,70,70,70,76,68,71,72,75,75,75,75,68,74,78,71,73,76,74,74,79,75,73,76,74\n",
    ",74,73,72,74,73,74,72,73,69,72,73,75,75,73,72,72,76,74,72,77,74,77,75,76,80,74,74,75,78,73,73,74,75,76,71,73,74,76,76,74,73,74,70,72,73,73,73,73\n",
    ",71,74,74,72,74,71,74,73,75,75,79,73,75,76,74,76,78,74,76,72,74,76,74,75,78,75,72,74,72,74,70,71,70,75,71,71,73,72,71,73,72,75,74,74,75,73,77,73\n",
    ",76,75,74,76,75,73,71,76])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [],
   "source": [
    "np_baseball = np.array([[74,180,74,215,72,210,72,210,73,188,69,176,69,209,71,200,76,231\n",
    ",71,180,73,188,73,180,74,185,74,160,69,180,70,185,73,189,75,185\n",
    ",78,219,79,230,76,205,74,230,76,195,72,180,71,192,75,225,77,203\n",
    ",74,195,73,182,74,188,78,200,73,180,75,200,73,200,75,245,75,240\n",
    ",74,215,69,185,71,175,74,199,73,200,73,215,76,200,74,205,74,206\n",
    ",70,186,72,188,77,220,74,210,70,195,73,200,75,200,76,212,76,224\n",
    ",78,210,74,205,74,220,76,195,77,200,81,260,78,228,75,270,77,200\n",
    ",75,210,76,190,74,220,72,180,72,205,75,210,73,220,73,211,73,200\n",
    ",70,180,70,190,70,170,76,230,68,155,71,185,72,185,75,200,75,225\n",
    ",75,225,75,220,68,160,74,205,78,235,71,250,73,210,76,190,74,160\n",
    ",74,200,79,205,75,222,73,195,76,205,74,220,74,220,73,170,72,185\n",
    ",74,195,73,220,74,230,72,180,73,220,69,180,72,180,73,170,75,210\n",
    ",75,215,73,200,72,213,72,180,76,192,74,235,72,185,77,235,74,210\n",
    ",77,222,75,210,76,230,80,220,74,180,74,190,75,200,78,210,73,194\n",
    ",73,180,74,190,75,240,76,200,71,198,73,200,74,195,76,210,76,220\n",
    ",74,190,73,210,74,225,70,180,72,185,73,170,73,185,73,185,73,180\n",
    ",71,178,74,175,74,200,72,204,74,211,71,190,74,210,73,190,75,190\n",
    ",75,185,79,290,73,175,75,185,76,200,74,220,76,170,78,220,74,190\n",
    ",76,220,72,205,74,200,76,250,74,225,75,215,78,210,75,215,72,195\n",
    ",74,200,72,194,74,220,70,180,71,180,70,170,75,195,71,180,71,170\n",
    ",73,206,72,205,71,200,73,225,72,201,75,225,74,233,74,180,75,225\n",
    ",73,180,77,220,73,180,76,237,75,215,74,190,76,235,75,190,73,180\n",
    ",71,165,76,195]]).reshape(200, 2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "74 inches\n",
      "74 inches\n",
      "72 inches\n",
      "72 inches\n",
      "73 inches\n",
      "69 inches\n",
      "69 inches\n",
      "71 inches\n",
      "76 inches\n",
      "71 inches\n",
      "73 inches\n",
      "73 inches\n",
      "74 inches\n",
      "74 inches\n",
      "69 inches\n",
      "70 inches\n",
      "73 inches\n",
      "75 inches\n",
      "78 inches\n",
      "79 inches\n",
      "76 inches\n",
      "74 inches\n",
      "76 inches\n",
      "72 inches\n",
      "71 inches\n",
      "75 inches\n",
      "77 inches\n",
      "74 inches\n",
      "73 inches\n",
      "74 inches\n",
      "78 inches\n",
      "73 inches\n",
      "75 inches\n",
      "73 inches\n",
      "75 inches\n",
      "75 inches\n",
      "74 inches\n",
      "69 inches\n",
      "71 inches\n",
      "74 inches\n",
      "73 inches\n",
      "73 inches\n",
      "76 inches\n",
      "74 inches\n",
      "74 inches\n",
      "70 inches\n",
      "72 inches\n",
      "77 inches\n",
      "74 inches\n",
      "70 inches\n",
      "73 inches\n",
      "75 inches\n",
      "76 inches\n",
      "76 inches\n",
      "78 inches\n",
      "74 inches\n",
      "74 inches\n",
      "76 inches\n",
      "77 inches\n",
      "81 inches\n",
      "78 inches\n",
      "75 inches\n",
      "77 inches\n",
      "75 inches\n",
      "76 inches\n",
      "74 inches\n",
      "72 inches\n",
      "72 inches\n",
      "75 inches\n",
      "73 inches\n",
      "73 inches\n",
      "73 inches\n",
      "70 inches\n",
      "70 inches\n",
      "70 inches\n",
      "76 inches\n",
      "68 inches\n",
      "71 inches\n",
      "72 inches\n",
      "75 inches\n",
      "75 inches\n",
      "75 inches\n",
      "75 inches\n",
      "68 inches\n",
      "74 inches\n",
      "78 inches\n",
      "71 inches\n",
      "73 inches\n",
      "76 inches\n",
      "74 inches\n",
      "74 inches\n",
      "79 inches\n",
      "75 inches\n",
      "73 inches\n",
      "76 inches\n",
      "74 inches\n",
      "74 inches\n",
      "73 inches\n",
      "72 inches\n",
      "74 inches\n",
      "73 inches\n",
      "74 inches\n",
      "72 inches\n",
      "73 inches\n",
      "69 inches\n",
      "72 inches\n",
      "73 inches\n",
      "75 inches\n",
      "75 inches\n",
      "73 inches\n",
      "72 inches\n",
      "72 inches\n",
      "76 inches\n",
      "74 inches\n",
      "72 inches\n",
      "77 inches\n",
      "74 inches\n",
      "77 inches\n",
      "75 inches\n",
      "76 inches\n",
      "80 inches\n",
      "74 inches\n",
      "74 inches\n",
      "75 inches\n",
      "78 inches\n",
      "73 inches\n",
      "73 inches\n",
      "74 inches\n",
      "75 inches\n",
      "76 inches\n",
      "71 inches\n",
      "73 inches\n",
      "74 inches\n",
      "76 inches\n",
      "76 inches\n",
      "74 inches\n",
      "73 inches\n",
      "74 inches\n",
      "70 inches\n",
      "72 inches\n",
      "73 inches\n",
      "73 inches\n",
      "73 inches\n",
      "73 inches\n",
      "71 inches\n",
      "74 inches\n",
      "74 inches\n",
      "72 inches\n",
      "74 inches\n",
      "71 inches\n",
      "74 inches\n",
      "73 inches\n",
      "75 inches\n",
      "75 inches\n",
      "79 inches\n",
      "73 inches\n",
      "75 inches\n",
      "76 inches\n",
      "74 inches\n",
      "76 inches\n",
      "78 inches\n",
      "74 inches\n",
      "76 inches\n",
      "72 inches\n",
      "74 inches\n",
      "76 inches\n",
      "74 inches\n",
      "75 inches\n",
      "78 inches\n",
      "75 inches\n",
      "72 inches\n",
      "74 inches\n",
      "72 inches\n",
      "74 inches\n",
      "70 inches\n",
      "71 inches\n",
      "70 inches\n",
      "75 inches\n",
      "71 inches\n",
      "71 inches\n",
      "73 inches\n",
      "72 inches\n",
      "71 inches\n",
      "73 inches\n",
      "72 inches\n",
      "75 inches\n",
      "74 inches\n",
      "74 inches\n",
      "75 inches\n",
      "73 inches\n",
      "77 inches\n",
      "73 inches\n",
      "76 inches\n",
      "75 inches\n",
      "74 inches\n",
      "76 inches\n",
      "75 inches\n",
      "73 inches\n",
      "71 inches\n",
      "76 inches\n",
      "74\n",
      "180\n",
      "74\n",
      "215\n",
      "72\n",
      "210\n",
      "72\n",
      "210\n",
      "73\n",
      "188\n",
      "69\n",
      "176\n",
      "69\n",
      "209\n",
      "71\n",
      "200\n",
      "76\n",
      "231\n",
      "71\n",
      "180\n",
      "73\n",
      "188\n",
      "73\n",
      "180\n",
      "74\n",
      "185\n",
      "74\n",
      "160\n",
      "69\n",
      "180\n",
      "70\n",
      "185\n",
      "73\n",
      "189\n",
      "75\n",
      "185\n",
      "78\n",
      "219\n",
      "79\n",
      "230\n",
      "76\n",
      "205\n",
      "74\n",
      "230\n",
      "76\n",
      "195\n",
      "72\n",
      "180\n",
      "71\n",
      "192\n",
      "75\n",
      "225\n",
      "77\n",
      "203\n",
      "74\n",
      "195\n",
      "73\n",
      "182\n",
      "74\n",
      "188\n",
      "78\n",
      "200\n",
      "73\n",
      "180\n",
      "75\n",
      "200\n",
      "73\n",
      "200\n",
      "75\n",
      "245\n",
      "75\n",
      "240\n",
      "74\n",
      "215\n",
      "69\n",
      "185\n",
      "71\n",
      "175\n",
      "74\n",
      "199\n",
      "73\n",
      "200\n",
      "73\n",
      "215\n",
      "76\n",
      "200\n",
      "74\n",
      "205\n",
      "74\n",
      "206\n",
      "70\n",
      "186\n",
      "72\n",
      "188\n",
      "77\n",
      "220\n",
      "74\n",
      "210\n",
      "70\n",
      "195\n",
      "73\n",
      "200\n",
      "75\n",
      "200\n",
      "76\n",
      "212\n",
      "76\n",
      "224\n",
      "78\n",
      "210\n",
      "74\n",
      "205\n",
      "74\n",
      "220\n",
      "76\n",
      "195\n",
      "77\n",
      "200\n",
      "81\n",
      "260\n",
      "78\n",
      "228\n",
      "75\n",
      "270\n",
      "77\n",
      "200\n",
      "75\n",
      "210\n",
      "76\n",
      "190\n",
      "74\n",
      "220\n",
      "72\n",
      "180\n",
      "72\n",
      "205\n",
      "75\n",
      "210\n",
      "73\n",
      "220\n",
      "73\n",
      "211\n",
      "73\n",
      "200\n",
      "70\n",
      "180\n",
      "70\n",
      "190\n",
      "70\n",
      "170\n",
      "76\n",
      "230\n",
      "68\n",
      "155\n",
      "71\n",
      "185\n",
      "72\n",
      "185\n",
      "75\n",
      "200\n",
      "75\n",
      "225\n",
      "75\n",
      "225\n",
      "75\n",
      "220\n",
      "68\n",
      "160\n",
      "74\n",
      "205\n",
      "78\n",
      "235\n",
      "71\n",
      "250\n",
      "73\n",
      "210\n",
      "76\n",
      "190\n",
      "74\n",
      "160\n",
      "74\n",
      "200\n",
      "79\n",
      "205\n",
      "75\n",
      "222\n",
      "73\n",
      "195\n",
      "76\n",
      "205\n",
      "74\n",
      "220\n",
      "74\n",
      "220\n",
      "73\n",
      "170\n",
      "72\n",
      "185\n",
      "74\n",
      "195\n",
      "73\n",
      "220\n",
      "74\n",
      "230\n",
      "72\n",
      "180\n",
      "73\n",
      "220\n",
      "69\n",
      "180\n",
      "72\n",
      "180\n",
      "73\n",
      "170\n",
      "75\n",
      "210\n",
      "75\n",
      "215\n",
      "73\n",
      "200\n",
      "72\n",
      "213\n",
      "72\n",
      "180\n",
      "76\n",
      "192\n",
      "74\n",
      "235\n",
      "72\n",
      "185\n",
      "77\n",
      "235\n",
      "74\n",
      "210\n",
      "77\n",
      "222\n",
      "75\n",
      "210\n",
      "76\n",
      "230\n",
      "80\n",
      "220\n",
      "74\n",
      "180\n",
      "74\n",
      "190\n",
      "75\n",
      "200\n",
      "78\n",
      "210\n",
      "73\n",
      "194\n",
      "73\n",
      "180\n",
      "74\n",
      "190\n",
      "75\n",
      "240\n",
      "76\n",
      "200\n",
      "71\n",
      "198\n",
      "73\n",
      "200\n",
      "74\n",
      "195\n",
      "76\n",
      "210\n",
      "76\n",
      "220\n",
      "74\n",
      "190\n",
      "73\n",
      "210\n",
      "74\n",
      "225\n",
      "70\n",
      "180\n",
      "72\n",
      "185\n",
      "73\n",
      "170\n",
      "73\n",
      "185\n",
      "73\n",
      "185\n",
      "73\n",
      "180\n",
      "71\n",
      "178\n",
      "74\n",
      "175\n",
      "74\n",
      "200\n",
      "72\n",
      "204\n",
      "74\n",
      "211\n",
      "71\n",
      "190\n",
      "74\n",
      "210\n",
      "73\n",
      "190\n",
      "75\n",
      "190\n",
      "75\n",
      "185\n",
      "79\n",
      "290\n",
      "73\n",
      "175\n",
      "75\n",
      "185\n",
      "76\n",
      "200\n",
      "74\n",
      "220\n",
      "76\n",
      "170\n",
      "78\n",
      "220\n",
      "74\n",
      "190\n",
      "76\n",
      "220\n",
      "72\n",
      "205\n",
      "74\n",
      "200\n",
      "76\n",
      "250\n",
      "74\n",
      "225\n",
      "75\n",
      "215\n",
      "78\n",
      "210\n",
      "75\n",
      "215\n",
      "72\n",
      "195\n",
      "74\n",
      "200\n",
      "72\n",
      "194\n",
      "74\n",
      "220\n",
      "70\n",
      "180\n",
      "71\n",
      "180\n",
      "70\n",
      "170\n",
      "75\n",
      "195\n",
      "71\n",
      "180\n",
      "71\n",
      "170\n",
      "73\n",
      "206\n",
      "72\n",
      "205\n",
      "71\n",
      "200\n",
      "73\n",
      "225\n",
      "72\n",
      "201\n",
      "75\n",
      "225\n",
      "74\n",
      "233\n",
      "74\n",
      "180\n",
      "75\n",
      "225\n",
      "73\n",
      "180\n",
      "77\n",
      "220\n",
      "73\n",
      "180\n",
      "76\n",
      "237\n",
      "75\n",
      "215\n",
      "74\n",
      "190\n",
      "76\n",
      "235\n",
      "75\n",
      "190\n",
      "73\n",
      "180\n",
      "71\n",
      "165\n",
      "76\n",
      "195\n"
     ]
    }
   ],
   "source": [
    "\n",
    "# Import numpy as np\n",
    "import numpy as np\n",
    "\n",
    "# For loop over np_height\n",
    "for x in np_height:\n",
    "    print(x,\"inches\")\n",
    "\n",
    "# For loop over np_baseball\n",
    "for x in np.nditer(np_baseball):\n",
    "    print(x)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Loop over DataFrame (1)\n",
    "Iterating over a Pandas DataFrame is typically done with the iterrows() method. Used in a for loop, every observation is iterated over and on every iteration the row label and actual row contents are available:\n",
    "\n",
    "```python\n",
    "for lab, row in brics.iterrows() :\n",
    "    ...\n",
    "```\n",
    "In this and the following exercises you will be working on the cars DataFrame. It contains information on the cars per capita and whether people drive right or left for seven countries in the world."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "US\n",
      "cars_per_cap              809\n",
      "country         United States\n",
      "drives_right             True\n",
      "Name: US, dtype: object\n",
      "AUS\n",
      "cars_per_cap          731\n",
      "country         Australia\n",
      "drives_right        False\n",
      "Name: AUS, dtype: object\n",
      "JAP\n",
      "cars_per_cap      588\n",
      "country         Japan\n",
      "drives_right    False\n",
      "Name: JAP, dtype: object\n",
      "IN\n",
      "cars_per_cap       18\n",
      "country         India\n",
      "drives_right    False\n",
      "Name: IN, dtype: object\n",
      "RU\n",
      "cars_per_cap       200\n",
      "country         Russia\n",
      "drives_right      True\n",
      "Name: RU, dtype: object\n",
      "MOR\n",
      "cars_per_cap         70\n",
      "country         Morocco\n",
      "drives_right       True\n",
      "Name: MOR, dtype: object\n",
      "EG\n",
      "cars_per_cap       45\n",
      "country         Egypt\n",
      "drives_right     True\n",
      "Name: EG, dtype: object\n"
     ]
    }
   ],
   "source": [
    "# Import cars data\n",
    "import pandas as pd\n",
    "cars = pd.read_csv('cars.csv', index_col = 0)\n",
    "\n",
    "# Iterate over rows of cars\n",
    "for row, value in cars.iterrows():\n",
    "    print(row)\n",
    "    print(value)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Loop over DataFrame (2)\n",
    "The row data that's generated by iterrows() on every run is a Pandas Series. This format is not very convenient to print out. Luckily, you can easily select variables from the Pandas Series using square brackets:\n",
    "\n",
    "```python\n",
    "for lab, row in brics.iterrows() :\n",
    "    print(row['country'])\n",
    "```"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "US: 809\n",
      "AUS: 731\n",
      "JAP: 588\n",
      "IN: 18\n",
      "RU: 200\n",
      "MOR: 70\n",
      "EG: 45\n"
     ]
    }
   ],
   "source": [
    "# Import cars data\n",
    "import pandas as pd\n",
    "cars = pd.read_csv('cars.csv', index_col = 0)\n",
    "\n",
    "# Adapt for loop\n",
    "for lab, row in cars.iterrows() :\n",
    "    print(lab,\": \",row['cars_per_cap'],sep = \"\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Add column (1)\n",
    "You can  add the length of the country names of the brics DataFrame in a new column:\n",
    "\n",
    "```python\n",
    "for lab, row in brics.iterrows() :\n",
    "    brics.loc[lab, \"name_length\"] = len(row[\"country\"])\n",
    "```\n",
    "You can do similar things on the cars DataFrame."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>cars_per_cap</th>\n",
       "      <th>country</th>\n",
       "      <th>drives_right</th>\n",
       "      <th>COUNTRY</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>US</th>\n",
       "      <td>809</td>\n",
       "      <td>United States</td>\n",
       "      <td>True</td>\n",
       "      <td>UNITED STATES</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>AUS</th>\n",
       "      <td>731</td>\n",
       "      <td>Australia</td>\n",
       "      <td>False</td>\n",
       "      <td>AUSTRALIA</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>JAP</th>\n",
       "      <td>588</td>\n",
       "      <td>Japan</td>\n",
       "      <td>False</td>\n",
       "      <td>JAPAN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>IN</th>\n",
       "      <td>18</td>\n",
       "      <td>India</td>\n",
       "      <td>False</td>\n",
       "      <td>INDIA</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>RU</th>\n",
       "      <td>200</td>\n",
       "      <td>Russia</td>\n",
       "      <td>True</td>\n",
       "      <td>RUSSIA</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>MOR</th>\n",
       "      <td>70</td>\n",
       "      <td>Morocco</td>\n",
       "      <td>True</td>\n",
       "      <td>MOROCCO</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>EG</th>\n",
       "      <td>45</td>\n",
       "      <td>Egypt</td>\n",
       "      <td>True</td>\n",
       "      <td>EGYPT</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "     cars_per_cap        country  drives_right        COUNTRY\n",
       "US            809  United States          True  UNITED STATES\n",
       "AUS           731      Australia         False      AUSTRALIA\n",
       "JAP           588          Japan         False          JAPAN\n",
       "IN             18          India         False          INDIA\n",
       "RU            200         Russia          True         RUSSIA\n",
       "MOR            70        Morocco          True        MOROCCO\n",
       "EG             45          Egypt          True          EGYPT"
      ]
     },
     "execution_count": 32,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Import cars data\n",
    "import pandas as pd\n",
    "cars = pd.read_csv('cars.csv', index_col = 0)\n",
    "\n",
    "# Code for loop that adds COUNTRY column\n",
    "for lab, row in cars.iterrows():\n",
    "    cars.loc[lab, \"COUNTRY\"] = row['country'].upper()\n",
    "\n",
    "\n",
    "# Print cars\n",
    "cars"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "Great, but you might remember that there is also an easier way to do this."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Add column (2)\n",
    "Using iterrows() to iterate over every observation of a Pandas DataFrame is easy to understand, but not very efficient. On every iteration, you're creating a new Pandas Series.\n",
    "\n",
    "If you want to add a column to a DataFrame by calling a function on another column, the iterrows() method in combination with a for loop is not the preferred way to go. Instead, you'll want to use apply().\n",
    "\n",
    "Compare the iterrows() version with the apply() version to get the same result in the brics DataFrame:\n",
    "\n",
    "```python\n",
    "for lab, row in brics.iterrows() :\n",
    "    brics.loc[lab, \"name_length\"] = len(row[\"country\"])\n",
    "\n",
    "brics[\"name_length\"] = brics[\"country\"].apply(len)\n",
    "```\n",
    "We can do a similar thing to call the upper() method on every name in the country column. However, upper() is a method, so we'll need a slightly different approach:\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>cars_per_cap</th>\n",
       "      <th>country</th>\n",
       "      <th>drives_right</th>\n",
       "      <th>COUNTRY</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>US</th>\n",
       "      <td>809</td>\n",
       "      <td>United States</td>\n",
       "      <td>True</td>\n",
       "      <td>UNITED STATES</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>AUS</th>\n",
       "      <td>731</td>\n",
       "      <td>Australia</td>\n",
       "      <td>False</td>\n",
       "      <td>AUSTRALIA</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>JAP</th>\n",
       "      <td>588</td>\n",
       "      <td>Japan</td>\n",
       "      <td>False</td>\n",
       "      <td>JAPAN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>IN</th>\n",
       "      <td>18</td>\n",
       "      <td>India</td>\n",
       "      <td>False</td>\n",
       "      <td>INDIA</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>RU</th>\n",
       "      <td>200</td>\n",
       "      <td>Russia</td>\n",
       "      <td>True</td>\n",
       "      <td>RUSSIA</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>MOR</th>\n",
       "      <td>70</td>\n",
       "      <td>Morocco</td>\n",
       "      <td>True</td>\n",
       "      <td>MOROCCO</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>EG</th>\n",
       "      <td>45</td>\n",
       "      <td>Egypt</td>\n",
       "      <td>True</td>\n",
       "      <td>EGYPT</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "     cars_per_cap        country  drives_right        COUNTRY\n",
       "US            809  United States          True  UNITED STATES\n",
       "AUS           731      Australia         False      AUSTRALIA\n",
       "JAP           588          Japan         False          JAPAN\n",
       "IN             18          India         False          INDIA\n",
       "RU            200         Russia          True         RUSSIA\n",
       "MOR            70        Morocco          True        MOROCCO\n",
       "EG             45          Egypt          True          EGYPT"
      ]
     },
     "execution_count": 34,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "cars = pd.read_csv('cars.csv', index_col = 0)\n",
    "\n",
    "# Use .apply(str.upper)\n",
    "cars['COUNTRY'] = cars['country'].apply(str.upper)\n",
    "cars"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Great job! It's time to blend everything you've learned together in a case-study. Head over to the next chapter!"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
